export type StatMods = {
  ATT?: number;
  TEC?: number;
  CHA?: number;
  DEF?: number;
  HEA?: number;
};

export type CharacterGraft = {
  id: string;
  name: string;
  sourceEnemy: string;
  ability: string;
  statBoost: StatMods;
  mutationCost: number;
  humanityLoss: number;
};

export const GRAFT_CATALOG: CharacterGraft[] = [
  {
    id: "cybernetic-laser-eye",
    name: "Cybernetic Laser Eye",
    sourceEnemy: "Optic Revenant",
    ability: "Fire a focused beam that reveals weak points through smoke and darkness.",
    statBoost: { TEC: 2, ATT: 1 },
    mutationCost: 2,
    humanityLoss: 6,
  },
  {
    id: "bone-rifle-arm",
    name: "Bone Rifle Arm",
    sourceEnemy: "Marrow Gunner",
    ability: "Your forearm unfolds into a living rifle that feeds on your pulse.",
    statBoost: { ATT: 3 },
    mutationCost: 3,
    humanityLoss: 9,
  },
  {
    id: "spider-spine",
    name: "Spider Spine",
    sourceEnemy: "Sprawl Widow",
    ability: "Deploy rear stabilizer limbs to climb walls and brace for recoil.",
    statBoost: { DEF: 2, TEC: 1 },
    mutationCost: 3,
    humanityLoss: 7,
  },
  {
    id: "neural-parasite",
    name: "Neural Parasite",
    sourceEnemy: "Static Leech",
    ability: "Latch into hostile systems and briefly hijack nearby electronics.",
    statBoost: { TEC: 3, CHA: -1 },
    mutationCost: 4,
    humanityLoss: 12,
  },
  {
    id: "shock-maw",
    name: "Shock Maw",
    sourceEnemy: "Wire Hound",
    ability: "A crackling bite discharges stored current into close targets.",
    statBoost: { ATT: 2, HEA: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "servo-tendon-weave",
    name: "Servo Tendon Weave",
    sourceEnemy: "Factory Strider",
    ability: "Micro-servos reinforce muscle pulls for brutal bursts of force.",
    statBoost: { ATT: 1, DEF: 1 },
    mutationCost: 1,
    humanityLoss: 3,
  },
  {
    id: "amalgam-hide",
    name: "Amalgam Hide",
    sourceEnemy: "Gutter Amalgam",
    ability: "Patchwork plating hardens under stress and sheds glancing blows.",
    statBoost: { DEF: 3 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "echo-lung",
    name: "Echo Lung",
    sourceEnemy: "Tunnel Howler",
    ability: "Exhale a disorienting sonic burst that rattles nerves and glass.",
    statBoost: { CHA: 1, HEA: 2 },
    mutationCost: 2,
    humanityLoss: 4,
  },
  {
    id: "phase-knuckles",
    name: "Phase Knuckles",
    sourceEnemy: "Blink Bruiser",
    ability: "Your fists slip through guard lines before solidifying on impact.",
    statBoost: { ATT: 3 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "memory-cyst",
    name: "Memory Cyst",
    sourceEnemy: "Archive Eater",
    ability: "Store enemy motion patterns and replay them as predictive instinct.",
    statBoost: { TEC: 1, CHA: 1 },
    mutationCost: 1,
    humanityLoss: 3,
  },
  {
    id: "carrion-filament-hair",
    name: "Carrion Filament Hair",
    sourceEnemy: "Signal Corpse",
    ability: "Fine tendrils sense motion in stale air and nearby vibrations.",
    statBoost: { TEC: 1, DEF: 1 },
    mutationCost: 1,
    humanityLoss: 2,
  },
  {
    id: "scavenger-gizzard",
    name: "Scavenger Gizzard",
    sourceEnemy: "Rust Feeder",
    ability: "Digest tainted water and spoiled rations without folding instantly.",
    statBoost: { HEA: 3 },
    mutationCost: 2,
    humanityLoss: 4,
  },
  {
    id: "hex-grid-skin",
    name: "Hex Grid Skin",
    sourceEnemy: "Shield Drone Saint",
    ability: "Your skin flashes a hex-pattern barrier for a split second when struck.",
    statBoost: { DEF: 3, TEC: 1 },
    mutationCost: 4,
    humanityLoss: 11,
  },
  {
    id: "rail-tongue",
    name: "Rail Tongue",
    sourceEnemy: "Track Licker",
    ability: "A whip-fast metallic tongue retrieves gear or lashes at close range.",
    statBoost: { ATT: 1, CHA: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "grave-sight-retina",
    name: "Grave-Sight Retina",
    sourceEnemy: "Morgue Oracle",
    ability: "See heat, fading footprints, and recent violence in the environment.",
    statBoost: { TEC: 3 },
    mutationCost: 3,
    humanityLoss: 7,
  },
  {
    id: "rebar-horns",
    name: "Rebar Horns",
    sourceEnemy: "Concrete Bull",
    ability: "Drive through cover or crowds with ugly, crushing momentum.",
    statBoost: { ATT: 2, DEF: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "suture-swarm",
    name: "Suture Swarm",
    sourceEnemy: "Patchmother",
    ability: "Microfilaments stitch wounds shut in the middle of combat.",
    statBoost: { HEA: 3, DEF: 1 },
    mutationCost: 4,
    humanityLoss: 14,
  },
  {
    id: "glass-vein-network",
    name: "Glass Vein Network",
    sourceEnemy: "Shard Saint",
    ability: "Transparent veins refract light and make your movements harder to read.",
    statBoost: { DEF: 1, CHA: 1 },
    mutationCost: 2,
    humanityLoss: 4,
  },
  {
    id: "boiler-heart",
    name: "Boiler Heart",
    sourceEnemy: "Steam Butcher",
    ability: "Overpressure your body for a violent surge of speed and aggression.",
    statBoost: { ATT: 3, HEA: 1 },
    mutationCost: 4,
    humanityLoss: 13,
  },
  {
    id: "hush-gland",
    name: "Hush Gland",
    sourceEnemy: "Silent Choir",
    ability: "Deadens your footsteps and muffles nearby movement for a brief window.",
    statBoost: { TEC: 1, CHA: 1 },
    mutationCost: 1,
    humanityLoss: 2,
  },
  {
    id: "coil-rib-cage",
    name: "Coil Rib Cage",
    sourceEnemy: "Metro Eel",
    ability: "Store charge in your torso and release it in a defensive arc.",
    statBoost: { DEF: 2, TEC: 2 },
    mutationCost: 3,
    humanityLoss: 9,
  },
  {
    id: "flare-glands",
    name: "Flare Glands",
    sourceEnemy: "Street Basilisk",
    ability: "Emit a blinding chemical flash from vents along the neck and jaw.",
    statBoost: { CHA: 1, TEC: 1 },
    mutationCost: 2,
    humanityLoss: 4,
  },
  {
    id: "pit-viper-vertebrae",
    name: "Pit Viper Vertebrae",
    sourceEnemy: "Pit Viper Saint",
    ability: "Your spine whips with predatory flexibility, improving dodges and lunges.",
    statBoost: { ATT: 1, DEF: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "static-beard",
    name: "Static Beard",
    sourceEnemy: "Breaker Hermit",
    ability: "Conductive whiskers detect current and humming machinery.",
    statBoost: { TEC: 2 },
    mutationCost: 1,
    humanityLoss: 2,
  },
  {
    id: "waste-filter-kidney",
    name: "Waste Filter Kidney",
    sourceEnemy: "Purple Drinker",
    ability: "Process toxins faster and shrug off low-grade contamination.",
    statBoost: { HEA: 3 },
    mutationCost: 2,
    humanityLoss: 4,
  },
  {
    id: "riot-anchor-shoulder",
    name: "Riot Anchor Shoulder",
    sourceEnemy: "Checkpoint Ogre",
    ability: "Absorb impacts and smash through barricades with a reinforced shoulder.",
    statBoost: { DEF: 3, ATT: 1 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "lantern-organ",
    name: "Lantern Organ",
    sourceEnemy: "Glow Saint",
    ability: "Project ghost-light from your chest cavity to reveal cloaked forms.",
    statBoost: { CHA: 1, TEC: 1 },
    mutationCost: 1,
    humanityLoss: 3,
  },
  {
    id: "scrap-mantis-blades",
    name: "Scrap Mantis Blades",
    sourceEnemy: "Mantis Collector",
    ability: "Folded arm blades spring out for savage close-quarters bursts.",
    statBoost: { ATT: 3 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "iron-lung-bellows",
    name: "Iron Lung Bellows",
    sourceEnemy: "Soot Diver",
    ability: "Store air and expel it in a concussive blast or survive longer in gas.",
    statBoost: { HEA: 2, DEF: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "mag-claw-fingertips",
    name: "Mag-Claw Fingertips",
    sourceEnemy: "Wall Crawler",
    ability: "Magnetic fingertips cling to rails, doors, and steel surfaces.",
    statBoost: { TEC: 1, DEF: 1 },
    mutationCost: 1,
    humanityLoss: 2,
  },
  {
    id: "copper-blood",
    name: "Copper Blood",
    sourceEnemy: "Volt Pilgrim",
    ability: "Trace weak currents through walls and survive minor electrical arcs.",
    statBoost: { HEA: 1, TEC: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "predator-pupil-array",
    name: "Predator Pupil Array",
    sourceEnemy: "Night Stalker",
    ability: "Multiple aperture shifts improve target tracking in chaos.",
    statBoost: { ATT: 1, TEC: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "crow-antennae",
    name: "Crow Antennae",
    sourceEnemy: "Broadcast Crow",
    ability: "Tune into weak radio chatter and ping encoded transmissions.",
    statBoost: { TEC: 2, CHA: 1 },
    mutationCost: 2,
    humanityLoss: 6,
  },
  {
    id: "slag-hooves",
    name: "Slag Hooves",
    sourceEnemy: "Foundry Goat",
    ability: "Kick sparks from concrete and hold steady on rubble and metal scrap.",
    statBoost: { DEF: 1, ATT: 1 },
    mutationCost: 1,
    humanityLoss: 3,
  },
  {
    id: "sainted-voice-box",
    name: "Sainted Voice Box",
    sourceEnemy: "Choir Machine",
    ability: "Layer speech with harmonics that unsettle enemies or rally crews.",
    statBoost: { CHA: 3 },
    mutationCost: 3,
    humanityLoss: 9,
  },
  {
    id: "ashen-marrow",
    name: "Ashen Marrow",
    sourceEnemy: "Cremator Wretch",
    ability: "Your bones retain heat, resisting cold and feeding explosive exertion.",
    statBoost: { HEA: 1, ATT: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "clockwork-liver",
    name: "Clockwork Liver",
    sourceEnemy: "Ticker Ghoul",
    ability: "Cycle stimulants and chems with less immediate backlash.",
    statBoost: { HEA: 3, CHA: -1 },
    mutationCost: 2,
    humanityLoss: 6,
  },
  {
    id: "signal-leech-palms",
    name: "Signal Leech Palms",
    sourceEnemy: "Patch Thief",
    ability: "Drain charge from terminals and dead devices through touch.",
    statBoost: { TEC: 3 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "breaker-jaw",
    name: "Breaker Jaw",
    sourceEnemy: "Demolition Saint",
    ability: "A reinforced bite can crush locks, bone, or cable restraints.",
    statBoost: { ATT: 3, DEF: 1 },
    mutationCost: 3,
    humanityLoss: 9,
  },
  {
    id: "shiver-sac",
    name: "Shiver Sac",
    sourceEnemy: "Cold Threader",
    ability: "Release a chill mist that slows pursuit and fogs thermal optics.",
    statBoost: { TEC: 1, CHA: 1 },
    mutationCost: 2,
    humanityLoss: 5,
  },
  {
    id: "vault-muscle-knots",
    name: "Vault Muscle Knots",
    sourceEnemy: "Safebreaker Titan",
    ability: "Dense muscle clusters let you force doors and carry absurd weight.",
    statBoost: { ATT: 3, HEA: 1 },
    mutationCost: 3,
    humanityLoss: 10,
  },
  {
    id: "whisper-mesh-ear",
    name: "Whisper Mesh Ear",
    sourceEnemy: "Vent Listener",
    ability: "Catch speech through walls, vents, and distant catwalks.",
    statBoost: { TEC: 1, CHA: 1 },
    mutationCost: 1,
    humanityLoss: 2,
  },
  {
    id: "needle-tail",
    name: "Needle Tail",
    sourceEnemy: "Sewer Scorpion",
    ability: "A hidden tail lashes out with venom or tracer compounds.",
    statBoost: { ATT: 3 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "cathedral-cartilage",
    name: "Cathedral Cartilage",
    sourceEnemy: "Bell Tower Giant",
    ability: "Elastic joint padding lets you survive drops and ugly impacts.",
    statBoost: { DEF: 3, HEA: 1 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "riot-siren-throat",
    name: "Riot Siren Throat",
    sourceEnemy: "Crowd Reaper",
    ability: "Unleash a shriek that disorients mobs and rattles augmented senses.",
    statBoost: { CHA: 3, TEC: 1 },
    mutationCost: 4,
    humanityLoss: 12,
  },
  {
    id: "wiretap-tongue",
    name: "Wiretap Tongue",
    sourceEnemy: "Cable Rat",
    ability: "Interface with exposed ports and jury-rig primitive data reads.",
    statBoost: { TEC: 3 },
    mutationCost: 2,
    humanityLoss: 6,
  },
  {
    id: "storm-capillaries",
    name: "Storm Capillaries",
    sourceEnemy: "Thunder Relic",
    ability: "Branching channels distribute power surges without frying you outright.",
    statBoost: { HEA: 1, TEC: 2 },
    mutationCost: 3,
    humanityLoss: 8,
  },
  {
    id: "grinder-patella",
    name: "Grinder Patella",
    sourceEnemy: "Grinder Hound",
    ability: "Reinforced knees turn leaps and slides into weapons.",
    statBoost: { ATT: 1, DEF: 1 },
    mutationCost: 1,
    humanityLoss: 3,
  },
  {
    id: "neon-bile-sac",
    name: "Neon Bile Sac",
    sourceEnemy: "Glow Maw",
    ability: "Spit corrosive fluorescent sludge that burns gear and morale alike.",
    statBoost: { ATT: 1, TEC: 1 },
    mutationCost: 2,
    humanityLoss: 6,
  },
  {
    id: "prayer-engine-node",
    name: "Prayer Engine Node",
    sourceEnemy: "Machine Devotee",
    ability: "A sacred logic kernel helps stabilize you under pressure and static.",
    statBoost: { CHA: 1, TEC: 2 },
    mutationCost: 2,
    humanityLoss: 6,
  },
  {
    id: "ferrofluid-spleen",
    name: "Ferrofluid Spleen",
    sourceEnemy: "Mercury Saint",
    ability: "Redistribute impact through metallic suspension inside the body.",
    statBoost: { DEF: 3, HEA: 1 },
    mutationCost: 3,
    humanityLoss: 9,
  },

  {
    id: "void-siphon-eye",
    name: "Void Siphon Eye",
    sourceEnemy: "Black Lens Apostle",
    ability: "Drain light from a small area, creating a pocket of artificial night.",
    statBoost: { TEC: 3, CHA: 1 },
    mutationCost: 4,
    humanityLoss: 14,
  },
  {
    id: "requiem-heart",
    name: "Requiem Heart",
    sourceEnemy: "Choir Butcher",
    ability: "When near death, your body surges with violent finality before collapsing.",
    statBoost: { ATT: 4, HEA: 1 },
    mutationCost: 5,
    humanityLoss: 16,
  },
  {
    id: "saint-killer-claws",
    name: "Saint-Killer Claws",
    sourceEnemy: "Cathedral Ravager",
    ability: "Extend serrated talons designed to tear armour and sacred plating.",
    statBoost: { ATT: 4 },
    mutationCost: 4,
    humanityLoss: 13,
  },
  {
    id: "mercy-hook-arm",
    name: "Mercy Hook Arm",
    sourceEnemy: "Dockside Penitent",
    ability: "A heavy hook-arm can drag enemies closer or anchor you in place.",
    statBoost: { ATT: 3, DEF: 1 },
    mutationCost: 3,
    humanityLoss: 10,
  },
  {
    id: "mirror-wasp-cluster",
    name: "Mirror Wasp Cluster",
    sourceEnemy: "Glass Hive Queen",
    ability: "Tiny reflective drones erupt from your flesh and harass nearby targets.",
    statBoost: { TEC: 3, CHA: 1 },
    mutationCost: 4,
    humanityLoss: 15,
  },
  {
    id: "funeral-smoke-lung",
    name: "Funeral Smoke Lung",
    sourceEnemy: "Ash Deacon",
    ability: "Exhale black smoke that hides movement and poisons weak air systems.",
    statBoost: { HEA: 2, CHA: 1 },
    mutationCost: 3,
    humanityLoss: 10,
  },
  {
    id: "gravitic-knot",
    name: "Gravitic Knot",
    sourceEnemy: "Collapsed Angel",
    ability: "Briefly distort local weight, pinning foes or lightening your own frame.",
    statBoost: { TEC: 4 },
    mutationCost: 5,
    humanityLoss: 18,
  },
  {
    id: "sacrament-spines",
    name: "Sacrament Spines",
    sourceEnemy: "Relic Flagellant",
    ability: "Launch barbed spinal shards that break off inside living tissue.",
    statBoost: { ATT: 4 },
    mutationCost: 4,
    humanityLoss: 14,
  },
  {
    id: "king-rat-cortex",
    name: "King Rat Cortex",
    sourceEnemy: "Sewer Monarch",
    ability: "Swarm-instinct lets you navigate tunnels and track movement in darkness.",
    statBoost: { TEC: 2, CHA: 2 },
    mutationCost: 3,
    humanityLoss: 11,
  },
  {
    id: "blasphemy-engine",
    name: "Blasphemy Engine",
    sourceEnemy: "Architect Heretic",
    ability: "A forbidden core overclocks all implanted systems for a short, brutal span.",
    statBoost: { ATT: 2, TEC: 2, DEF: 2 },
    mutationCost: 6,
    humanityLoss: 20,
  },
  {
    id: "catacomb-eye-cluster",
    name: "Catacomb Eye Cluster",
    sourceEnemy: "Bone Archivist",
    ability: "Additional wet eyes open across the skull, expanding perception in every direction.",
    statBoost: { TEC: 4, CHA: -1 },
    mutationCost: 4,
    humanityLoss: 13,
  },
  {
    id: "hallowed-battery-rack",
    name: "Hallowed Battery Rack",
    sourceEnemy: "Sanctum Artillery",
    ability: "Store unstable energy cells within the ribcage and vent them as a blast.",
    statBoost: { ATT: 3, TEC: 2 },
    mutationCost: 5,
    humanityLoss: 17,
  },
  {
    id: "riot-god-knees",
    name: "Riot God Knees",
    sourceEnemy: "Stampede Idol",
    ability: "Explosive lower limbs turn charges, jumps, and impact landings into attacks.",
    statBoost: { ATT: 2, DEF: 2 },
    mutationCost: 4,
    humanityLoss: 12,
  },
  {
    id: "angelwire-halo",
    name: "Angelwire Halo",
    sourceEnemy: "Halo Warden",
    ability: "A spinning filament crown intercepts projectiles and shreds nearby flesh.",
    statBoost: { DEF: 4, TEC: 1 },
    mutationCost: 5,
    humanityLoss: 18,
  },
  {
    id: "gravebell-throat",
    name: "Gravebell Throat",
    sourceEnemy: "Bell Saint",
    ability: "Your voice tolls like a funeral bell, staggering enemies and breaking morale.",
    statBoost: { CHA: 4 },
    mutationCost: 4,
    humanityLoss: 13,
  },
  {
    id: "sawtooth-gizzard",
    name: "Sawtooth Gizzard",
    sourceEnemy: "Meat Harvester",
    ability: "Digest organic matter with terrifying efficiency to recover after carnage.",
    statBoost: { HEA: 4 },
    mutationCost: 4,
    humanityLoss: 14,
  },
  {
    id: "chapel-bone-plating",
    name: "Chapel Bone Plating",
    sourceEnemy: "Ivory Zealot",
    ability: "Dense white plating grows beneath the skin like internal armour pews.",
    statBoost: { DEF: 4 },
    mutationCost: 4,
    humanityLoss: 14,
  },
  {
    id: "apex-predator-gland",
    name: "Apex Predator Gland",
    sourceEnemy: "Crown Devourer",
    ability: "Flood your body with hunting chemistry when you smell blood or fear.",
    statBoost: { ATT: 4, HEA: 1 },
    mutationCost: 5,
    humanityLoss: 16,
  },
  {
    id: "oracle-worm",
    name: "Oracle Worm",
    sourceEnemy: "Data Prophet",
    ability: "A living thread inside the skull whispers predictions, lies, and route maps.",
    statBoost: { TEC: 3, CHA: 2 },
    mutationCost: 5,
    humanityLoss: 17,
  },
  {
    id: "soul-furnace",
    name: "Soul Furnace",
    sourceEnemy: "Crucible King",
    ability: "Burn through stored life and anguish to supercharge your body for one terrible moment.",
    statBoost: { ATT: 3, TEC: 3, HEA: 2 },
    mutationCost: 7,
    humanityLoss: 25,
  },
];

export function getGraftTotals(grafts: CharacterGraft[] | undefined): Required<StatMods> {
  const safe = Array.isArray(grafts) ? grafts : [];

  return safe.reduce(
    (acc, graft) => {
      acc.ATT += graft.statBoost?.ATT ?? 0;
      acc.TEC += graft.statBoost?.TEC ?? 0;
      acc.CHA += graft.statBoost?.CHA ?? 0;
      acc.DEF += graft.statBoost?.DEF ?? 0;
      acc.HEA += graft.statBoost?.HEA ?? 0;
      return acc;
    },
    { ATT: 0, TEC: 0, CHA: 0, DEF: 0, HEA: 0 }
  );
}

export function getTotalMutationFromGrafts(grafts: CharacterGraft[] | undefined): number {
  const safe = Array.isArray(grafts) ? grafts : [];
  return safe.reduce((sum, graft) => sum + (graft.mutationCost ?? 0), 0);
}

export function getTotalHumanityLossFromGrafts(grafts: CharacterGraft[] | undefined): number {
  const safe = Array.isArray(grafts) ? grafts : [];
  return safe.reduce((sum, graft) => sum + (graft.humanityLoss ?? 0), 0);
}